// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/proto/test.proto

/*
Package liuyangc3_golangtest_project_grpc_service is a generated protocol buffer package.

It is generated from these files:
	grpc/proto/test.proto

It has these top-level messages:
	GetProjectRequest
	ProjectMessage
*/
package liuyangc3_golangtest_project_grpc_service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetProjectRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetProjectRequest) Reset()                    { *m = GetProjectRequest{} }
func (m *GetProjectRequest) String() string            { return proto.CompactTextString(m) }
func (*GetProjectRequest) ProtoMessage()               {}
func (*GetProjectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetProjectRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ProjectMessage struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *ProjectMessage) Reset()                    { *m = ProjectMessage{} }
func (m *ProjectMessage) String() string            { return proto.CompactTextString(m) }
func (*ProjectMessage) ProtoMessage()               {}
func (*ProjectMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ProjectMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProjectMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*GetProjectRequest)(nil), "liuyangc3.golangtest.grpc.grpc.service.GetProjectRequest")
	proto.RegisterType((*ProjectMessage)(nil), "liuyangc3.golangtest.grpc.grpc.service.ProjectMessage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ProjectService service

type ProjectServiceClient interface {
	GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*ProjectMessage, error)
}

type projectServiceClient struct {
	cc *grpc.ClientConn
}

func NewProjectServiceClient(cc *grpc.ClientConn) ProjectServiceClient {
	return &projectServiceClient{cc}
}

func (c *projectServiceClient) GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*ProjectMessage, error) {
	out := new(ProjectMessage)
	err := grpc.Invoke(ctx, "/liuyangc3.golangtest.grpc.grpc.service.ProjectService/GetProject", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProjectService service

type ProjectServiceServer interface {
	GetProject(context.Context, *GetProjectRequest) (*ProjectMessage, error)
}

func RegisterProjectServiceServer(s *grpc.Server, srv ProjectServiceServer) {
	s.RegisterService(&_ProjectService_serviceDesc, srv)
}

func _ProjectService_GetProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liuyangc3.golangtest.grpc.grpc.service.ProjectService/GetProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetProject(ctx, req.(*GetProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProjectService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "liuyangc3.golangtest.grpc.grpc.service.ProjectService",
	HandlerType: (*ProjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProject",
			Handler:    _ProjectService_GetProject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto/test.proto",
}

func init() { proto.RegisterFile("grpc/proto/test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0x28, 0xca, 0xcf,
	0x4a, 0x4d, 0x2e, 0xd1, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2f, 0x49, 0x2d, 0x2e, 0xd1, 0x03,
	0x33, 0x85, 0x34, 0x73, 0x32, 0x4b, 0x2b, 0x13, 0xf3, 0xd2, 0x93, 0x8d, 0xf5, 0xd2, 0xf3, 0x73,
	0x12, 0xf3, 0xd2, 0x61, 0x72, 0x20, 0xe5, 0x7a, 0xe9, 0x45, 0x05, 0xc9, 0x7a, 0xc5, 0xa9, 0x45,
	0x65, 0x99, 0xc9, 0xa9, 0x52, 0x32, 0xe9, 0xf9, 0xf9, 0xe9, 0x39, 0xa9, 0xfa, 0x89, 0x05, 0x99,
	0xfa, 0x89, 0x79, 0x79, 0xf9, 0x25, 0x89, 0x25, 0x99, 0xf9, 0x79, 0xc5, 0x10, 0x83, 0x94, 0x94,
	0xb9, 0x04, 0xdd, 0x53, 0x4b, 0x02, 0x20, 0x1a, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84,
	0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x98, 0x32, 0x53, 0x94,
	0x4c, 0xb8, 0xf8, 0xa0, 0x2a, 0x7c, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0xd1, 0x55, 0x08, 0x09,
	0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x81, 0x45, 0xc0, 0x6c, 0xa3, 0xcd, 0x8c, 0x70,
	0x6d, 0xc1, 0x10, 0xb7, 0x08, 0x2d, 0x60, 0xe4, 0xe2, 0x42, 0x58, 0x27, 0x64, 0xa3, 0x47, 0xb4,
	0x37, 0xf4, 0x30, 0x5c, 0x29, 0x65, 0x49, 0x82, 0x6e, 0x54, 0xe7, 0x2b, 0x49, 0x36, 0x5d, 0x7e,
	0x32, 0x99, 0x49, 0x58, 0x48, 0x50, 0xbf, 0xcc, 0x50, 0x1f, 0xaa, 0xa1, 0x58, 0xbf, 0x3a, 0x33,
	0xa5, 0x36, 0x89, 0x0d, 0x1c, 0x2e, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x49, 0x12,
	0xf2, 0x7c, 0x01, 0x00, 0x00,
}
