- name: update Python
  hosts: "{{ host }}"
  remote_user: root

  tasks:
    - name download Python source
      command: wget https://www.python.org/ftp/python/2.7.10/Python-2.7.10.tar.xz
      
    - name: copy Python scouce to target
      copy: src=Python-2.7.10.tar.xz dest=/tmp/

    - name: unzip Python source
      command: tar xf /tmp/Python-2.7.10.tar.xz -C /tmp

    - name: update Python
      command: chdir=/tmp/Python-2.7.10 {{ item }}
      with_items:
      - ./configure --prefix=/usr/local
      - /usr/bin/make
      - /usr/bin/make altinstall
      - rm -f /usr/local/bin/python
      - /bin/ln -s /usr/local/bin/python2.7 /usr/local/bin/python
